# Generated by Django 4.2.6 on 2024-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('NBI', 'Nairobi'), ('MSA', 'Mombasa'), ('KSM', 'Kisumu'), ('KMB', 'Kiambu'), ('KWL', 'Kwale'), ('KLF', 'Kilifi'), ('TRV', 'Tana River'), ('LMU', 'Lamu'), ('TVT', 'Taita Taveta'), ('GRS', 'Garissa'), ('WJR', 'Wajir'), ('MDR', 'Mandera'), ('MRS', 'Marsabit'), ('ISL', 'Isiolo'), ('MRU', 'Meru'), ('TNT', 'Tharaka-Nithi'), ('EMB', 'Embu'), ('KTU', 'Kitui'), ('MCK', 'Machakos'), ('MKN', 'Makueni'), ('NDR', 'Nyandarua'), ('NYR', 'Nyeri'), ('KRG', 'Kirinyaga'), ('MRG', 'Muranga'), ('TRK', 'Turkana'), ('WPK', 'West Pokot'), ('SBR', 'Samburu'), ('TNZ', 'Trans Nzoia'), ('UGS', 'Uasin Gishu'), ('EMK', 'Elgeyo Marakwet'), ('NDI', 'Nandi'), ('BRG', 'Baringo'), ('LKP', 'Laikipia'), ('NKR', 'Nakuru'), ('NRK', 'Narok'), ('KJD', 'Kajiado'), ('KRC', 'Kericho'), ('BMT', 'Bomet'), ('KKG', 'Kakamega'), ('VHG', 'Vihiga'), ('BGM', 'Bungoma'), ('BSA', 'Busia'), ('SYA', 'Siaya'), ('HBY', 'Homa Bay'), ('MGR', 'Migori'), ('KSI', 'Kisii'), ('NMR', 'Nyamira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='year'),
        ),
    ]
