# Generated by Django 4.2.6 on 2024-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Foreign Used', 'Foreign Used'), ('Kenyan Used', 'Kenyan Used')], max_length=100),
        ),
    ]
