# Generated by Django 4.2.6 on 2024-01-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=50),
        ),
    ]
